const d = (sectionKey, label, type, value, order, group) => ({
  pageKey: "home",
  sectionKey,
  label,
  type,
  value,
  order,
  group,
});

const defaults = [
  d("hero-eyebrow","Hero eyebrow","text",`Medically Supervised · Women Only`,10,"Hero"),
  d("hero-heading-line1","Hero heading line 1","text",`Movement is`,11,"Hero"),
  d("hero-heading-line2","Hero heading line 2","text",`medicine —`,12,"Hero"),
  d("hero-heading-emphasis","Hero highlighted word","text",`not`,13,"Hero"),
  d("hero-heading-line3","Hero heading line 3","text",`a debt you pay`,14,"Hero"),
  d("hero-heading-line4","Hero heading line 4","text",`for eating.`,15,"Hero"),
  d("hero-subheading","Hero description","textarea",`A medically supervised weight-loss program built for women's biology — real meal plans, a private support community, and results that last. Over 700 women have already started.`,16,"Hero"),
  d("hero-primary-label","Hero primary button","text",`Start Your Journey`,17,"Hero"),
  d("hero-primary-link","Hero primary link","link",`/pricing#apply`,18,"Hero"),
  d("hero-secondary-label","Hero secondary button","text",`See How It Works`,19,"Hero"),
  d("hero-secondary-link","Hero secondary link","link",`/program`,20,"Hero"),
  d("hero-trust-1","Hero trust item 1","text",`700+ women helped`,21,"Hero"),
  d("hero-trust-2","Hero trust item 2","text",`Medically supervised`,22,"Hero"),
  d("hero-trust-3","Hero trust item 3","text",`Private women-only community`,23,"Hero"),
  d("hero-image","Hero image","image",`https://images.unsplash.com/photo-1550259979-ed79b48d2a30?w=900&q=85&auto=format`,24,"Hero"),
  d("hero-image-alt","Hero image alt text","text",`Confident Black woman exercising in gym — Khairo Diet Clinic member`,25,"Hero"),
  d("hero-stat","Hero stat","text",`700+`,26,"Hero"),
  d("hero-stat-label","Hero stat label","text",`Women transformed`,27,"Hero"),

  d("method-eyebrow","Method eyebrow","text",`The Khairo Diet Clinic Method`,40,"Method"),
  d("method-title","Method heading","text",`Four things working<br/>together. That's the difference.`,41,"Method"),
  d("method-subtitle","Method subtitle","textarea",`This isn't a diet plan. It's a system built around your biology, your accountability, and your life.`,42,"Method"),
  d("method-pillar-1-title","Method pillar 1 title","text",`Medical Supervision`,43,"Method"),
  d("method-pillar-1-body","Method pillar 1 text","textarea",`Your program is overseen by a health professional, not generic advice off the internet.`,44,"Method"),
  d("method-pillar-2-title","Method pillar 2 title","text",`Personalized Meal Plans`,45,"Method"),
  d("method-pillar-2-body","Method pillar 2 text","textarea",`Real food, built around your body, your goals, and your routine — no starvation, no fads.`,46,"Method"),
  d("method-pillar-3-title","Method pillar 3 title","text",`Accountability Group`,47,"Method"),
  d("method-pillar-3-body","Method pillar 3 text","textarea",`A private women-only community that keeps you consistent on the hard days.`,48,"Method"),
  d("method-pillar-4-title","Method pillar 4 title","text",`Proven Results`,49,"Method"),
  d("method-pillar-4-body","Method pillar 4 text","textarea",`Join 700+ women who've already changed their relationship with their bodies.`,50,"Method"),

  d("how-eyebrow","Process eyebrow","text",`The Process`,60,"How It Works"),
  d("how-title","Process heading","text",`How it works`,61,"How It Works"),
  d("how-subtitle","Process subtitle","textarea",`Four simple steps between you and a body that feels like home.`,62,"How It Works"),

  d("how-step-1-title","Step 1 title","text",`Apply`,63,"How It Works"),
  d("how-step-1-body","Step 1 text","textarea",`Tell us about your goals in a 2-minute application. No pressure, no judgment.`,64,"How It Works"),
  d("how-step-1-image","Step 1 image","image",`https://images.unsplash.com/photo-1550259979-ed79b48d2a30?w=800&q=85&auto=format`,65,"How It Works"),
  d("how-step-1-image-alt","Step 1 image alt","text",`Black woman smiling while using her phone to apply`,66,"How It Works"),

  d("how-step-2-title","Step 2 title","text",`Assessment`,67,"How It Works"),
  d("how-step-2-body","Step 2 text","textarea",`A medically guided review of where you are and what your body needs.`,68,"How It Works"),
  d("how-step-2-image","Step 2 image","image",`https://images.unsplash.com/photo-1758526214005-acd3ec7560e2?w=800&q=85&auto=format`,69,"How It Works"),
  d("how-step-2-image-alt","Step 2 image alt","text",`Two Black women in a wellness consultation`,70,"How It Works"),

  d("how-step-3-title","Step 3 title","text",`Your Plan + Your People`,71,"How It Works"),
  d("how-step-3-body","Step 3 text","textarea",`Get your personalized meal plan and join the private support group the same week.`,72,"How It Works"),
  d("how-step-3-image","Step 3 image","image",`https://images.unsplash.com/photo-1575467678950-0c09aad418af?w=800&q=85&auto=format`,73,"How It Works"),
  d("how-step-3-image-alt","Step 3 image alt","text",`Black woman preparing a healthy meal`,74,"How It Works"),

  d("how-step-4-title","Step 4 title","text",`Track & Transform`,75,"How It Works"),
  d("how-step-4-body","Step 4 text","textarea",`Weekly check-ins, real adjustments, and a community cheering you on.`,76,"How It Works"),
  d("how-step-4-image","Step 4 image","image",`https://images.unsplash.com/photo-1631899560971-394ded28a80f?w=800&q=85&auto=format`,77,"How It Works"),
  d("how-step-4-image-alt","Step 4 image alt","text",`Black woman running and tracking her progress`,78,"How It Works"),

  d("results-eyebrow","Results eyebrow","text",`Real Results`,90,"Results"),
  d("results-title","Results heading","text",`Real women. Real, lasting change.`,91,"Results"),
  d("results-subtitle","Results subtitle","textarea",`Every story here is from a real woman in the program. Individual results vary.`,92,"Results"),

  d("results-1-name","Result 1 name","text",`Chiamaka O.`,93,"Results"),
  d("results-1-stat","Result 1 result","text",`Lost 11kg`,94,"Results"),
  d("results-1-period","Result 1 period","text",`in 14 weeks`,95,"Results"),
  d("results-1-before","Result 1 before image","image",`https://images.unsplash.com/photo-1569925444984-9e2e5fc3d1fb?w=400&q=80&auto=format`,96,"Results"),
  d("results-1-after","Result 1 after image","image",`https://images.unsplash.com/photo-1507152927179-bc4ebfef7103?w=400&q=80&auto=format`,97,"Results"),
  d("results-1-quote","Result 1 quote","textarea",`I finally feel confident in my own skin.`,98,"Results"),

  d("results-2-name","Result 2 name","text",`Ngozi A.`,99,"Results"),
  d("results-2-stat","Result 2 result","text",`Lost 8kg`,100,"Results"),
  d("results-2-period","Result 2 period","text",`in 10 weeks`,101,"Results"),
  d("results-2-before","Result 2 before image","image",`https://images.unsplash.com/photo-1550259979-ed79b48d2a30?w=400&q=80&auto=format`,102,"Results"),
  d("results-2-after","Result 2 after image","image",`https://images.unsplash.com/photo-1631899477678-9d3c5aeded2d?w=400&q=80&auto=format`,103,"Results"),
  d("results-2-quote","Result 2 quote","textarea",`The accountability group kept me going.`,104,"Results"),

  d("results-3-name","Result 3 name","text",`Funke B.`,105,"Results"),
  d("results-3-stat","Result 3 result","text",`Lost 6kg`,106,"Results"),
  d("results-3-period","Result 3 period","text",`in 8 weeks`,107,"Results"),
  d("results-3-before","Result 3 before image","image",`https://images.unsplash.com/photo-1575467678950-0c09aad418af?w=400&q=80&auto=format`,108,"Results"),
  d("results-3-after","Result 3 after image","image",`https://images.unsplash.com/photo-1603503363848-6952525df449?w=400&q=80&auto=format`,109,"Results"),
  d("results-3-quote","Result 3 quote","textarea",`Medical guidance made it feel safe and real.`,110,"Results"),
  d("results-button-label","Results button","text",`See More Transformations →`,111,"Results"),
  d("results-disclaimer","Results disclaimer","textarea",`Individual results vary. Results shown are from real program participants.`,112,"Results"),

  d("testimonials-eyebrow","Testimonials eyebrow","text",`What They Say`,120,"Testimonials"),
  d("testimonials-title","Testimonials heading","text",`700+ women.<br/>One community.`,121,"Testimonials"),

  d("testimonial-1-quote","Testimonial 1 quote","textarea",`I finally stopped seeing food as something to earn. Down 9kg and I actually feel free.`,122,"Testimonials"),
  d("testimonial-1-name","Testimonial 1 name","text",`Aisha O.`,123,"Testimonials"),
  d("testimonial-1-tag","Testimonial 1 program","text",`Core Program · 12 weeks`,124,"Testimonials"),
  d("testimonial-1-rating","Testimonial 1 rating","text",`5`,125,"Testimonials"),
  d("testimonial-1-avatar","Testimonial 1 image","image",`https://images.unsplash.com/photo-1507152927179-bc4ebfef7103?w=100&q=80&auto=format`,126,"Testimonials"),

  d("testimonial-2-quote","Testimonial 2 quote","textarea",`The group is everything. On the days I wanted to quit, they showed up for me. I've never had that in a fitness program before.`,127,"Testimonials"),
  d("testimonial-2-name","Testimonial 2 name","text",`Ngozi A.`,128,"Testimonials"),
  d("testimonial-2-tag","Testimonial 2 program","text",`Plus Program · 8 weeks`,129,"Testimonials"),
  d("testimonial-2-rating","Testimonial 2 rating","text",`5`,130,"Testimonials"),
  d("testimonial-2-avatar","Testimonial 2 image","image",`https://images.unsplash.com/photo-1569925444984-9e2e5fc3d1fb?w=100&q=80&auto=format`,131,"Testimonials"),

  d("testimonial-3-quote","Testimonial 3 quote","textarea",`Medically guided made all the difference — it felt safe, not extreme. I lost 7kg without starving myself once.`,132,"Testimonials"),
  d("testimonial-3-name","Testimonial 3 name","text",`Funke B.`,133,"Testimonials"),
  d("testimonial-3-tag","Testimonial 3 program","text",`VIP Program · 10 weeks`,134,"Testimonials"),
  d("testimonial-3-rating","Testimonial 3 rating","text",`4`,135,"Testimonials"),
  d("testimonial-3-avatar","Testimonial 3 image","image",`https://images.unsplash.com/photo-1550259979-ed79b48d2a30?w=100&q=80&auto=format`,136,"Testimonials"),

  d("testimonial-4-quote","Testimonial 4 quote","textarea",`The meal plans are actually delicious. I didn't feel like I was dieting at all, just eating better.`,137,"Testimonials"),
  d("testimonial-4-name","Testimonial 4 name","text",`Adaeze K.`,138,"Testimonials"),
  d("testimonial-4-tag","Testimonial 4 program","text",`Core Program · 10 weeks`,139,"Testimonials"),
  d("testimonial-4-rating","Testimonial 4 rating","text",`5`,140,"Testimonials"),
  d("testimonial-4-avatar","Testimonial 4 image","image",`https://images.unsplash.com/photo-1603503363848-6952525df449?w=100&q=80&auto=format`,141,"Testimonials"),

  d("coach-image","Coach image","image",`https://images.unsplash.com/photo-1603503363848-6952525df449?w=700&q=85&auto=format`,150,"Coach"),
  d("coach-image-alt","Coach image alt","text",`Khairo Diet Clinic Coach Ada — fitness and wellness expert`,151,"Coach"),
  d("coach-eyebrow","Coach eyebrow","text",`Your Guide`,152,"Coach"),
  d("coach-name","Coach name","text",`Coach Ada`,153,"Coach"),
  d("coach-role","Coach title","text",`Women's Health & Weight-Loss Specialist`,154,"Coach"),
  d("coach-bio-1","Coach biography 1","textarea",`After years of watching women struggle with programs built for men's biology, Coach Ada created Khairo Diet Clinic with a single goal: a program that works with how women's bodies actually function. Hormones, hunger signals, metabolism — all of it factored in from day one.`,155,"Coach"),
  d("coach-bio-2","Coach biography 2","textarea",`More than 700 women have completed Khairo Diet Clinic under her medical guidance. The program isn't about perfection — it's about building a relationship with your body that lasts.`,156,"Coach"),
  d("coach-credential-1","Coach credential 1","text",`Medically trained`,157,"Coach"),
  d("coach-credential-2","Coach credential 2","text",`700+ clients`,158,"Coach"),
  d("coach-credential-3","Coach credential 3","text",`Women's health focus`,159,"Coach"),

  d("pricing-eyebrow","Pricing eyebrow","text",`Simple Pricing`,170,"Pricing"),
  d("pricing-title","Pricing heading","text",`Your investment<br/>in yourself.`,171,"Pricing"),
  d("pricing-subtitle","Pricing subtitle","textarea",`No hidden fees. No lock-ins. Pay per cycle, stop whenever you're ready.`,172,"Pricing"),
  d("pricing-core-description","Core description","textarea",`Everything you need to start your transformation.`,173,"Pricing"),
  d("pricing-core-cta","Core button","text",`Get Started`,174,"Pricing"),
  d("pricing-plus-description","Plus description","textarea",`The full program with medical oversight built in.`,175,"Pricing"),
  d("pricing-plus-cta","Plus button","text",`Apply for Plus`,176,"Pricing"),
  d("pricing-vip-description","VIP description","textarea",`White-glove support for the fastest, safest results.`,177,"Pricing"),
  d("pricing-vip-cta","VIP button","text",`Apply for VIP`,178,"Pricing"),
  d("pricing-help-prefix","Pricing help text","text",`Not sure which plan is right?`,179,"Pricing"),
  d("pricing-help-link","Pricing help link text","text",`Chat with us on WhatsApp`,180,"Pricing"),
  d("pricing-help-suffix","Pricing help ending","text",`— we'll guide you.`,181,"Pricing"),

  d("faq-eyebrow","FAQ eyebrow","text",`Questions`,190,"FAQ"),
  d("faq-title","FAQ heading","text",`Everything you're wondering.`,191,"FAQ"),
  d("faq-subtitle","FAQ subtitle","textarea",`Can't find what you're looking for? Chat with us on WhatsApp.`,192,"FAQ"),

  d("faq-1-q","FAQ 1 question","text",`Is this safe — is it really medically supervised?`,193,"FAQ"),
  d("faq-1-a","FAQ 1 answer","textarea",`Yes. Every Khairo Diet Clinic program is overseen by a trained health professional who reviews your intake form, monitors your progress, and can adjust your plan based on how your body responds. It's not a generic diet — it's a guided health journey.`,194,"FAQ"),
  d("faq-2-q","FAQ 2 question","text",`Do I have to exercise a lot?`,195,"FAQ"),
  d("faq-2-a","FAQ 2 answer","textarea",`No. Movement helps (remember Lac-Phe — the molecule that naturally quiets hunger neurons), but the program is built around sustainable habits, not punishment. We'll recommend movement that fits your life, not a brutal gym schedule.`,196,"FAQ"),
  d("faq-3-q","FAQ 3 question","text",`Is it only for women?`,197,"FAQ"),
  d("faq-3-a","FAQ 3 answer","textarea",`Yes — the program and community are designed exclusively for women. This creates a safe, judgment-free space where members can be honest about their bodies, their struggles, and their progress.`,198,"FAQ"),
  d("faq-4-q","FAQ 4 question","text",`How do I get started?`,199,"FAQ"),
  d("faq-4-a","FAQ 4 answer","textarea",`Apply in about 2 minutes using the form on this page or by messaging us on WhatsApp. We'll guide you through a short onboarding, assign your plan, and add you to the private support group — usually within the same week.`,200,"FAQ"),
  d("faq-5-q","FAQ 5 question","text",`What if I've tried every diet and failed before?`,201,"FAQ"),
  d("faq-5-a","FAQ 5 answer","textarea",`That's exactly who this is for. Most programs fail women because they're built around restriction, not biology. Khairo Diet Clinic addresses the hormonal and metabolic reasons weight loss stalls — so this time, it's different.`,202,"FAQ"),
  d("faq-6-q","FAQ 6 question","text",`What do I actually get in the meal plan?`,203,"FAQ"),
  d("faq-6-a","FAQ 6 answer","textarea",`A realistic, personalized eating plan built around your food preferences, budget, and goals. Real Nigerian foods, practical portions, and no starvation. Plans are adjusted as your body changes.`,204,"FAQ"),

  d("cta-eyebrow","CTA eyebrow","text",`Your Time is Now`,220,"Final CTA"),
  d("cta-title-line1","CTA heading line 1","text",`Your last “first day”`,221,"Final CTA"),
  d("cta-title-line2","CTA heading line 2","text",`starts here.`,222,"Final CTA"),
  d("cta-body","CTA description","textarea",`Join 700+ women who stopped dieting and started living.`,223,"Final CTA"),
  d("cta-primary-label","CTA button","text",`Start Your Journey`,224,"Final CTA"),
  d("cta-primary-link","CTA button link","link",`/pricing#apply`,225,"Final CTA"),
  d("cta-whatsapp-label","CTA WhatsApp button","text",`Chat on WhatsApp`,226,"Final CTA"),
];

export default defaults;
